//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestureMapper
    {
        public int GestureMapperID { get; set; }
        public int UserID { get; set; }
        public int LanguageID { get; set; }
        public int GestureID { get; set; }
        public int VoiceTypeID { get; set; }
        public string Voice { get; set; }
    
        public virtual Gesture Gesture { get; set; }
        public virtual Language Language { get; set; }
        public virtual User User { get; set; }
        public virtual VoiceType VoiceType { get; set; }
    }
}
